export const copy = {
  appName: "Pé-de-meia",
  appTagline: "Suas finanças, um dia de cada vez.",
  calendarTitle: "Calendário financeiro",
  calendarSubtitle: "Acompanhe receitas e despesas diárias de forma visual.",
  auth: {
    loginTitle: "Bem-vindo de volta",
    loginDescription: "Entre para gerenciar suas finanças diárias.",
    registerTitle: "Crie sua conta",
    registerDescription: "Comece a registrar receitas e despesas no calendário.",
    email: "E-mail",
    password: "Senha",
    name: "Nome",
    signIn: "Entrar",
    signOut: "Sair",
    createAccount: "Criar conta",
    pleaseWait: "Aguarde...",
    noAccount: "Ainda não tem conta?",
    signUp: "Cadastre-se",
    hasAccount: "Já tem uma conta?",
    invalidCredentials: "E-mail ou senha inválidos",
  },
  entry: {
    new: "Novo lançamento",
    edit: "Editar lançamento",
    description: "Registre uma receita ou despesa no calendário.",
    type: "Tipo",
    income: "Receita",
    expense: "Despesa",
    amount: "Valor",
    date: "Data",
    category: "Categoria",
    categoryPlaceholder: "Selecione uma categoria",
    note: "Observação",
    notePlaceholder: "Observação opcional",
    cancel: "Cancelar",
    create: "Criar",
    update: "Atualizar",
    saving: "Salvando...",
    saveError: "Não foi possível salvar o lançamento",
  },
  daySheet: {
    titleFallback: "Detalhes do dia",
    description: "Revise e gerencie os lançamentos deste dia.",
    income: "Receitas",
    expense: "Despesas",
    net: "Saldo",
    entries: "Lançamentos",
    addEntry: "Adicionar",
    loading: "Carregando lançamentos...",
    empty: "Nenhum lançamento neste dia.",
    loadError: "Não foi possível carregar os lançamentos",
    deleteError: "Não foi possível excluir o lançamento",
    editEntry: "Editar lançamento",
    deleteEntry: "Excluir lançamento",
    confirmDelete: "Excluir",
  },
  calendar: {
    newEntry: "Novo lançamento",
    updating: "Atualizando calendário...",
    loadError: "Não foi possível carregar o calendário",
  },
  period: {
    income: "Receitas no período",
    expense: "Despesas no período",
    net: "Saldo do período",
  },
  toast: {
    entryCreated: "Lançamento criado",
    entryUpdated: "Lançamento atualizado",
    entryDeleted: "Lançamento excluído",
    genericError: "Algo deu errado. Tente novamente.",
  },
  deleteConfirm: {
    title: "Excluir lançamento?",
    description:
      "Esta ação não pode ser desfeita. O lançamento será removido permanentemente.",
    cancel: "Cancelar",
    confirm: "Excluir",
    deleting: "Excluindo...",
  },
} as const;
