export const copy = {
  appName: "Pé-de-meia",
  appTagline: "Suas finanças, um dia de cada vez.",
  calendarTitle: "Calendário financeiro",
  calendarSubtitle: "Acompanhe receitas e despesas diárias de forma visual.",
  auth: {
    loginTitle: "Bem-vindo de volta",
    loginDescription: "Entre para gerenciar suas finanças diárias.",
    registerTitle: "Crie sua conta",
    registerDescription: "Comece a registrar receitas e despesas no calendário.",
    email: "E-mail",
    password: "Senha",
    name: "Nome",
    signIn: "Entrar",
    signOut: "Sair",
    createAccount: "Criar conta",
    pleaseWait: "Aguarde...",
    noAccount: "Ainda não tem conta?",
    signUp: "Cadastre-se",
    hasAccount: "Já tem uma conta?",
    invalidCredentials: "E-mail ou senha inválidos",
    loginRequired: "Faça login para acessar esta página.",
    demoTitle: "Conta demo para testes",
    demoEmail: "E-mail:",
    demoSignIn: "Entrar com conta demo",
    passwordHint: "Mínimo de 8 caracteres.",
  },
  entry: {
    new: "adicionar",
    newIncome: "Nova entrada",
    newExpense: "Nova saída",
    edit: "editar",
    description: "Registre uma receita ou despesa no calendário.",
    type: "Tipo",
    income: "Receita",
    expense: "Despesa",
    amount: "Valor",
    date: "data",
    category: "Categoria",
    categoryPlaceholder: "Selecione uma categoria",
    tags: "tags",
    note: "Observação",
    notePlaceholder: "nome",
    recurring: "Recorrente",
    doesNotRepeat: "não repete",
    repeats: "recorrente",
    recurringHint: (day: number) => `Repete todo mês no dia ${day}`,
    installments: "parcelas",
    installmentOnce: "à vista",
    installmentTimes: (count: number) => `${count}x`,
    cancel: "Cancelar",
    create: "Criar",
    update: "Atualizar",
    addAction: "adicionar",
    saving: "Salvando...",
    saveError: "Não foi possível salvar o lançamento",
  },
  daySheet: {
    titleFallback: "Detalhes do dia",
    description: "Revise e gerencie os lançamentos deste dia.",
    income: "Receitas",
    expense: "Despesas",
    net: "Saldo",
    entries: "Lançamentos",
    addEntry: "Adicionar",
    close: "Fechar",
    loading: "Carregando lançamentos...",
    empty: "Nenhum lançamento neste dia.",
    loadError: "Não foi possível carregar os lançamentos",
    deleteError: "Não foi possível excluir o lançamento",
    editEntry: "Editar",
    deleteEntry: "Excluir",
    rowMenu: "Mais ações",
    confirmDelete: "Excluir",
  },
  calendar: {
    newEntry: "Novo lançamento",
    updating: "Atualizando calendário...",
    loadError: "Não foi possível carregar o calendário",
    clickDayHint: "Clique em um dia para ver ou adicionar lançamentos.",
    clickDayHintDismiss: "Entendi",
    newEntryForDate: "Novo lançamento ·",
    today: "Hoje",
  },
  deleteConfirm: {
    title: "Excluir lançamento?",
    description:
      "Esta ação não pode ser desfeita. O lançamento será removido permanentemente.",
    cancel: "Cancelar",
    confirm: "Excluir",
    deleting: "Excluindo...",
  },
  nav: {
    saldos: "Saldos",
    totais: "Totais",
    horizonte: "Projeção",
    horizonteHint: "Saldo projetado nos próximos meses",
    calendar: "Calendário",
    categories: "Tags",
    gastosFixos: "Gastos fixos",
    menu: "Menu",
    sectionDaily: "Dia a dia",
    sectionOrganize: "Organizar",
    goToday: "Ir pra hoje",
    collapseSidebar: "Recolher menu",
    expandSidebar: "Expandir menu",
  },
  ledger: {
    title: "Saldos",
    subtitle: "Sua planilha de caixa — entradas, saídas e saldo dia a dia.",
    emptyTitle: "Sua planilha está pronta",
    emptyDescription:
      "Cada linha é um dia do mês. Clique em uma célula para registrar um gasto ou receita, ou configure contas fixas em Gastos fixos.",
    emptyActionRecurring: "Configurar contas fixas",
    emptyActionHint: "Use Totais para acompanhar o progresso do mês.",
    day: "Dia",
    income: "Entradas",
    expense: "Saídas",
    daily: "Diários",
    savings: "Economias",
    card: "Cartão",
    balance: "Saldo",
    total: "Total",
    prevMonth: "Mês anterior",
    nextMonth: "Próximo mês",
    prevDay: "Dia anterior",
    nextDay: "Próximo dia",
    filterColumn: "Coluna",
    filterAll: "Todos",
    viewIncome: "Ver entradas do dia",
    viewExpense: "Ver saídas do dia",
    viewDaily: "Ver diários do dia",
    viewSavings: "Ver economias do dia",
    viewCard: "Ver cartão do dia",
    addIncome: "Adicionar entrada",
    addExpense: "Adicionar saída",
    addDaily: "Adicionar diário",
    addSavings: "Adicionar economia",
    addCard: "Adicionar cartão",
    openDay: "Ver lançamentos do dia",
  },
  empty: {
    calendarTitle: "Nenhum lançamento neste período",
    calendarDescription:
      "Comece registrando uma receita ou despesa, ou configure contas fixas.",
    calendarAction: "Novo lançamento",
    dayTitle: "Dia sem lançamentos",
    dayDescription: "Adicione a primeira receita ou despesa deste dia.",
  },
  categories: {
    title: "Tags",
    subtitle: "Organize receitas e despesas com tags e orçamentos mensais.",
    intro:
      "Tags classificam seus lançamentos. Ex.: Moradia → conta fixa; Mercado → gasto do dia; Netflix → cartão.",
    income: "Receitas",
    expense: "Despesas",
    new: "Nova tag",
    edit: "Editar tag",
    name: "Nome",
    color: "Cor",
    type: "Tipo",
    budget: "Orçamento do mês",
    budgetPlaceholder: "Sem orçamento",
    saveBudget: "Salvar",
    budgetMonthLabel: "Orçamentos de",
    budgetHint: "Defina um limite mensal por tag de despesa.",
    ledgerColumn: "Tipo de movimento",
    setBudget: "Definir orçamento",
    empty: "Nenhuma tag cadastrada.",
    deleteTitle: "Excluir categoria?",
    deleteDescription:
      "Categorias com lançamentos não podem ser excluídas. Esta ação não pode ser desfeita.",
    create: "Criar",
    update: "Atualizar",
    cancel: "Cancelar",
    delete: "Excluir",
  },
  gastosFixos: {
    title: "Gastos fixos",
    subtitle:
      "Contas que se repetem todo mês e o orçamento para gastos do dia a dia.",
    tabFixed: "Contas fixas",
    tabDailyBudget: "Orçamento diário",
  },
  fixedExpenses: {
    title: "Contas fixas",
    subtitle:
      "Despesas que saem da conta todo mês — aluguel, internet, telefone, faculdade.",
    new: "Nova conta fixa",
    edit: "Editar conta fixa",
    dayOfMonth: "Dia do vencimento",
    active: "Ativa",
    inactive: "Inativa",
    empty: "Nenhuma conta fixa cadastrada.",
    deleteTitle: "Excluir conta fixa?",
    deleteDescription:
      "Novos meses não receberão este lançamento. Lançamentos já criados permanecem no calendário.",
    everyMonth: "Todo dia",
    listSummary: (day: number, start: string, end: string) =>
      `Vencimento dia ${day} · ${start} a ${end}`,
  },
  period: {
    income: "Receitas no período",
    expense: "Despesas no período",
    net: "Saldo do período",
    budget: "Orçamento de despesas",
    budgetUsed: "utilizado",
  },
  toast: {
    entryCreated: "Lançamento criado",
    entryUpdated: "Lançamento atualizado",
    entryDeleted: "Lançamento excluído",
    categoryCreated: "Categoria criada",
    categoryUpdated: "Categoria atualizada",
    categoryDeleted: "Categoria excluída",
    budgetSaved: "Orçamento salvo",
    fixedExpenseCreated: "Conta fixa criada",
    fixedExpenseUpdated: "Conta fixa atualizada",
    fixedExpenseDeleted: "Conta fixa excluída",
    genericError: "Algo deu errado. Tente novamente.",
    success: "Salvo com sucesso",
  },
  totals: {
    title: "Totais do mês",
    subtitle: "Performance, economia e custo de vida em um só lugar.",
    performance: "Performance",
    saved: "Economizado",
    costOfLiving: "Custo de vida",
    dailyAverage: "Diário médio",
    movements: "Movimentações",
    totalIncome: "Entradas totais",
    totalExpense: "Saídas totais",
    configureDailyCeiling: "Configurar orçamento diário",
  },
  horizon: {
    title: "Projeção",
    subtitle:
      "Veja como seu saldo evolui nos próximos meses com base no que já configurou.",
    legendTitle: "Legenda",
    legendNegative: "Saldo negativo",
    legendLow: "Saldo baixo",
    legendHealthy: "Saldo saudável",
    legendProjected: "Dia projetado",
    legendRecurring: "Com conta fixa",
    months3: "3 meses",
    months6: "6 meses",
    months12: "12 meses",
    goToday: "Ir pra hoje",
    summaryToday: "Saldo hoje",
    summaryEnd: "Saldo no fim do horizonte",
    summaryLowest: "Ponto mais baixo",
    summaryFirstNegative: "Primeiro dia negativo",
    noNegativeDays: "Nenhum dia negativo projetado",
    projectedDay: "Projetado",
    actualDay: "Realizado",
    recurringDay: "Conta fixa prevista",
    outOfRange: "Fora do horizonte",
    deltaLabel: "Variação do dia",
  },
  dailyBudget: {
    title: "Orçamento diário",
    subtitle:
      "Quanto você pretende gastar por mês em mercado, lazer, transporte e outros gastos do dia a dia.",
    intro:
      "O app calcula um teto por dia na planilha. Aluguel, contas e cartão ficam em Contas fixas.",
    examples: "Ex.: mercado, combustível, delivery, lazer",
    dailyCeiling: "Teto por dia",
    monthlyExpenses: "Itens do orçamento",
    monthlyTotal: "Total mensal",
    dividedBy: "dividido por",
    days: (count: number) => `${count} dias`,
    divisorDays: "Dividir por",
    addExpense: "Adicionar item",
    newExpense: "Novo item",
    editExpense: "Editar item",
    name: "Nome",
    amount: "Orçamento mensal",
    amountHint: "Quanto você costuma gastar por mês neste tipo de gasto.",
    empty: "Nenhum item cadastrado.",
    edit: "Editar",
    delete: "Excluir",
    rowMenu: "Mais ações",
    saved: "Orçamento salvo",
    deleted: "Item removido",
  },
  domain: {
    columnHint: {
      INCOME: "Entra na conta corrente neste dia.",
      EXPENSE: "Conta paga da conta — aluguel, internet, boletos.",
      DAILY: "Gasto à vista — sai do caixa hoje.",
      SAVINGS: "Transferência para reserva — sai do caixa hoje.",
      CARD: "Compra no crédito — entra na fatura, não no saldo hoje.",
    },
    cardKind: {
      commitment: "compromisso",
      payment: "pagamento",
    },
  },
  menu: {
    title: "Menu",
    subtitle: "Perfil, cartão e configurações.",
    back: "Voltar ao menu",
    profile: "Perfil",
    settings: "Configurações",
    dailyBudget: "Orçamento diário",
    card: "Cartão de crédito",
    cardDescription: "Fechamento, vencimento e como a fatura funciona.",
    subscription: "Assinatura",
    terms: "Termos de uso",
    privacy: "Política de privacidade",
    feedback: "Enviar sugestão",
    feedbackEmail: "contato@pedemeia.dev",
    subscriptionTrial: "Período de teste",
    subscriptionActive: "Assinatura ativa",
    subscriptionCancelled: "Assinatura cancelada",
    subscriptionExpired: "Assinatura expirada",
  },
  settings: {
    title: "Configurações",
    subtitle: "Saldo inicial, cartão e preferências de cálculo.",
    openingBalance: "Saldo inicial",
    openingBalanceHint: "Usado como ponto de partida na planilha e projeções.",
    dailyDivisor: "Dias no mês (orçamento diário)",
    cardSection: "Cartão de crédito",
    cardClosingDay: "Dia de fechamento",
    cardDueDay: "Dia de vencimento",
    cardHint:
      "Compras até o fechamento entram na fatura que vence neste dia. Vale para novas compras.",
    save: "Salvar configurações",
    saved: "Configurações salvas",
  },
  profile: {
    title: "Perfil",
    subtitle: "Seus dados de conta.",
    name: "Nome",
    email: "E-mail",
    save: "Salvar perfil",
    saved: "Perfil atualizado",
  },
  onboarding: {
    title: "Vamos organizar suas finanças",
    subtitle: "Em poucos passos você configura o essencial antes de usar a planilha.",
    skip: "Pular e ir para Saldos",
    back: "Voltar",
    next: "Continuar",
    finish: "Ir para Saldos",
    stepOf: (current: number, total: number) => `Passo ${current} de ${total}`,
    stepBalanceTitle: "Saldo inicial",
    stepBalanceDescription:
      "Quanto você tem na conta corrente hoje? Esse valor é o ponto de partida da planilha.",
    stepBalanceLabel: "Saldo na conta",
    stepFixedTitle: "Contas fixas",
    stepFixedDescription:
      "Cadastre despesas que se repetem todo mês com valor e dia de vencimento — aluguel, internet, telefone, faculdade.",
    stepFixedAdd: "Adicionar conta fixa",
    stepFixedName: "Nome",
    stepFixedAmount: "Valor",
    stepFixedDay: "Dia do vencimento",
    stepFixedDayShort: "Dia",
    stepFixedRemove: "Remover conta",
    stepFixedEmpty: "Nenhuma conta cadastrada. Adicione a primeira abaixo.",
    stepFixedExamples: "Ex.: Aluguel, Internet, Telefone, Faculdade",
    stepFixedSkipHint: "Você pode pular e configurar depois em Gastos fixos.",
    stepDailyTitle: "Gastos do dia a dia",
    stepDailyDescription:
      "Defina quanto costuma gastar por mês em mercado, lazer, transporte e similares. O app calcula um teto diário.",
    stepDailyAdd: "Adicionar item",
    stepDailyName: "Nome",
    stepDailyAmount: "Orçamento mensal",
    stepDailyRemove: "Remover item",
    stepDailyEmpty: "Nenhum item cadastrado. Adicione o primeiro abaixo.",
    stepDailyExamples: "Ex.: Mercado, Delivery, Lazer",
    stepDailySkipHint: "Configure depois em Gastos fixos → Orçamento diário.",
    stepCardTitle: "Cartão de crédito",
    stepCardDescription:
      "Compras no crédito não saem do saldo hoje — só no dia do pagamento da fatura.",
    stepCardClosing: "Dia de fechamento",
    stepCardDue: "Dia de vencimento",
    stepCardHint:
      "Compras até o fechamento entram na fatura que vence no dia informado.",
    stepHowToTitle: "Como usar no dia a dia",
    stepHowToDescription: "Três atalhos para sua rotina noturna:",
    stepHowToSaldos:
      "Saldos — sua planilha de caixa. Clique em um dia para lançar gastos e receitas.",
    stepHowToTotais:
      "Totais — acompanhe o progresso do mês e quanto ainda pode gastar por dia.",
    stepHowToRecurring:
      "Gastos fixos — ajuste contas fixas e orçamento diário quando algo mudar.",
  },
} as const;
