export const copy = {
  appName: "Pé-de-meia",
  appTagline: "Suas finanças, um dia de cada vez.",
  calendarTitle: "Calendário financeiro",
  calendarSubtitle: "Acompanhe receitas e despesas diárias de forma visual.",
  auth: {
    loginTitle: "Bem-vindo de volta",
    loginDescription: "Entre para gerenciar suas finanças diárias.",
    registerTitle: "Crie sua conta",
    registerDescription: "Comece a registrar receitas e despesas no calendário.",
    email: "E-mail",
    password: "Senha",
    name: "Nome",
    signIn: "Entrar",
    signOut: "Sair",
    createAccount: "Criar conta",
    pleaseWait: "Aguarde...",
    noAccount: "Ainda não tem conta?",
    signUp: "Cadastre-se",
    hasAccount: "Já tem uma conta?",
    invalidCredentials: "E-mail ou senha inválidos",
    loginRequired: "Faça login para acessar esta página.",
    demoTitle: "Conta demo para testes",
    demoEmail: "E-mail:",
    demoSignIn: "Entrar com conta demo",
    passwordHint: "Mínimo de 8 caracteres.",
  },
  entry: {
    new: "Novo lançamento",
    newIncome: "Nova entrada",
    newExpense: "Nova saída",
    edit: "Editar lançamento",
    description: "Registre uma receita ou despesa no calendário.",
    type: "Tipo",
    income: "Receita",
    expense: "Despesa",
    amount: "Valor",
    date: "Data",
    category: "Categoria",
    categoryPlaceholder: "Selecione uma categoria",
    note: "Observação",
    notePlaceholder: "Observação opcional",
    recurring: "Recorrente",
    recurringHint: (day: number) => `Repete todo mês no dia ${day}`,
    cancel: "Cancelar",
    create: "Criar",
    update: "Atualizar",
    saving: "Salvando...",
    saveError: "Não foi possível salvar o lançamento",
  },
  daySheet: {
    titleFallback: "Detalhes do dia",
    description: "Revise e gerencie os lançamentos deste dia.",
    income: "Receitas",
    expense: "Despesas",
    net: "Saldo",
    entries: "Lançamentos",
    addEntry: "Adicionar",
    loading: "Carregando lançamentos...",
    empty: "Nenhum lançamento neste dia.",
    loadError: "Não foi possível carregar os lançamentos",
    deleteError: "Não foi possível excluir o lançamento",
    editEntry: "Editar lançamento",
    deleteEntry: "Excluir lançamento",
    confirmDelete: "Excluir",
  },
  calendar: {
    newEntry: "Novo lançamento",
    updating: "Atualizando calendário...",
    loadError: "Não foi possível carregar o calendário",
    clickDayHint: "Clique em um dia para ver ou adicionar lançamentos.",
    clickDayHintDismiss: "Entendi",
    newEntryForDate: "Novo lançamento ·",
    today: "Hoje",
  },
  deleteConfirm: {
    title: "Excluir lançamento?",
    description:
      "Esta ação não pode ser desfeita. O lançamento será removido permanentemente.",
    cancel: "Cancelar",
    confirm: "Excluir",
    deleting: "Excluindo...",
  },
  nav: {
    saldos: "Saldos",
    totais: "Totais",
    horizonte: "Horizonte",
    calendar: "Calendário",
    categories: "Tags",
    recurring: "Recorrentes",
    menu: "Menu",
    goToday: "Ir pra hoje",
    collapseSidebar: "Recolher menu",
    expandSidebar: "Expandir menu",
  },
  ledger: {
    title: "Planilha de saldos",
    subtitle: "Acompanhe entradas, saídas e saldo acumulado dia a dia.",
    day: "Dia",
    income: "Entradas",
    expense: "Saídas",
    daily: "Diários",
    savings: "Economias",
    card: "Cartão",
    balance: "Saldo",
    total: "Total",
    prevMonth: "Mês anterior",
    nextMonth: "Próximo mês",
    prevDay: "Dia anterior",
    nextDay: "Próximo dia",
    filterType: "Filtrar por tipo",
    filterAll: "Todos",
    addIncome: "Adicionar entrada",
    addExpense: "Adicionar saída",
    openDay: "Ver lançamentos do dia",
  },
  empty: {
    calendarTitle: "Nenhum lançamento neste período",
    calendarDescription:
      "Comece registrando uma receita ou despesa, ou configure lançamentos recorrentes.",
    calendarAction: "Novo lançamento",
    dayTitle: "Dia sem lançamentos",
    dayDescription: "Adicione a primeira receita ou despesa deste dia.",
  },
  categories: {
    title: "Tags",
    subtitle: "Organize receitas e despesas com tags e orçamentos mensais.",
    income: "Receitas",
    expense: "Despesas",
    new: "Nova categoria",
    edit: "Editar categoria",
    name: "Nome",
    color: "Cor",
    type: "Tipo",
    budget: "Orçamento do mês",
    budgetPlaceholder: "Sem orçamento",
    saveBudget: "Salvar",
    budgetMonthLabel: "Orçamentos de",
    budgetHint: "Defina um limite mensal por categoria de despesa.",
    ledgerColumn: "Coluna contábil",
    setBudget: "Definir orçamento",
    empty: "Nenhuma categoria cadastrada.",
    deleteTitle: "Excluir categoria?",
    deleteDescription:
      "Categorias com lançamentos não podem ser excluídas. Esta ação não pode ser desfeita.",
    create: "Criar",
    update: "Atualizar",
    cancel: "Cancelar",
    delete: "Excluir",
  },
  recurring: {
    title: "Lançamentos recorrentes",
    subtitle:
      "Defina receitas e despesas fixas. Elas são aplicadas automaticamente ao abrir o calendário.",
    new: "Nova recorrência",
    edit: "Editar recorrência",
    dayOfMonth: "Dia do mês",
    active: "Ativa",
    inactive: "Inativa",
    empty: "Nenhuma recorrência configurada.",
    deleteTitle: "Excluir recorrência?",
    deleteDescription:
      "Novos meses não receberão este lançamento. Lançamentos já criados permanecem no calendário.",
    everyMonth: "Todo dia",
  },
  period: {
    income: "Receitas no período",
    expense: "Despesas no período",
    net: "Saldo do período",
    budget: "Orçamento de despesas",
    budgetUsed: "utilizado",
  },
  toast: {
    entryCreated: "Lançamento criado",
    entryUpdated: "Lançamento atualizado",
    entryDeleted: "Lançamento excluído",
    categoryCreated: "Categoria criada",
    categoryUpdated: "Categoria atualizada",
    categoryDeleted: "Categoria excluída",
    budgetSaved: "Orçamento salvo",
    recurringCreated: "Recorrência criada",
    recurringUpdated: "Recorrência atualizada",
    recurringDeleted: "Recorrência excluída",
    genericError: "Algo deu errado. Tente novamente.",
    success: "Salvo com sucesso",
  },
  totals: {
    title: "Totais do mês",
    subtitle: "Performance, economia e custo de vida em um só lugar.",
    performance: "Performance",
    saved: "Economizado",
    costOfLiving: "Custo de vida",
    dailyAverage: "Diário médio",
    movements: "Movimentações",
    totalIncome: "Entradas totais",
    totalExpense: "Saídas totais",
    configureDailyCeiling: "Configurar previsão de diário",
  },
  horizon: {
    title: "Horizonte de saldos",
    subtitle:
      "Grade dia × mês com saldo projetado. Calendário completo fica em Calendário.",
    legendTitle: "Legenda",
    legendNegative: "Saldo negativo",
    legendLow: "Saldo baixo",
    legendHealthy: "Saldo saudável",
    legendProjected: "Dia projetado",
    legendRecurring: "Com recorrente",
    months3: "3 meses",
    months6: "6 meses",
    months12: "12 meses",
    goToday: "Ir pra hoje",
    summaryToday: "Saldo hoje",
    summaryEnd: "Saldo no fim do horizonte",
    summaryLowest: "Ponto mais baixo",
    summaryFirstNegative: "Primeiro dia negativo",
    noNegativeDays: "Nenhum dia negativo projetado",
    projectedDay: "Projetado",
    actualDay: "Realizado",
    recurringDay: "Recorrente previsto",
    outOfRange: "Fora do horizonte",
    deltaLabel: "Variação do dia",
  },
  forecast: {
    title: "Previsão de diário",
    subtitle: "Calcule seu teto diário a partir de gastos fixos mensais.",
    dailyCeiling: "Teto diário",
    divisorDays: "Dividir por",
    addExpense: "Adicionar gasto fixo",
    newExpense: "Novo gasto fixo",
    editExpense: "Editar gasto fixo",
    name: "Nome",
    amount: "Valor mensal",
    empty: "Nenhum gasto fixo cadastrado.",
    edit: "Editar",
    delete: "Excluir",
    saved: "Gasto fixo salvo",
    deleted: "Gasto fixo excluído",
  },
  menu: {
    title: "Menu",
    subtitle: "Perfil, configurações e mais.",
    profile: "Perfil",
    settings: "Configurações",
    forecast: "Previsão de diário",
    subscription: "Assinatura",
    terms: "Termos de uso",
    privacy: "Política de privacidade",
    feedback: "Enviar sugestão",
    feedbackEmail: "contato@pedemeia.dev",
    subscriptionTrial: "Período de teste",
    subscriptionActive: "Assinatura ativa",
    subscriptionCancelled: "Assinatura cancelada",
    subscriptionExpired: "Assinatura expirada",
  },
  settings: {
    title: "Configurações",
    subtitle: "Saldo inicial e preferências de cálculo.",
    openingBalance: "Saldo inicial",
    openingBalanceHint: "Usado como ponto de partida na planilha e projeções.",
    dailyDivisor: "Divisor de dias (previsão)",
    save: "Salvar configurações",
    saved: "Configurações salvas",
  },
  profile: {
    title: "Perfil",
    subtitle: "Seus dados de conta.",
    name: "Nome",
    email: "E-mail",
    save: "Salvar perfil",
    saved: "Perfil atualizado",
  },
} as const;
